# Generated by Django 3.2.15 on 2022-09-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=500)),
                ('nombre', models.CharField(default='None', max_length=500, null=True)),
                ('rol', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField(default=False)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido')),
            ],
        ),
    ]
