# Generated by Django 3.2.15 on 2022-09-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='pedido_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido'),
        ),
    ]
